server:
  port: 9000

spring:
  application:
    name: goorm.form
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/goorm.form?serverTimezone=UTC
    username: root
    password: saokiritoni
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: always
  jackson:
    default-property-inclusion: non_null

logging:
  level:
    org.springframework.jdbc: debug
